### ISSUE TITLE
Tonomy SSO - home page - user stories

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#209]
The Tonomy SSO website needs a home page for when you visit it, not in the SSO flow

Ideas:

- a bit about Tonomy account
- how to get Tonomy ID
- Tonomy ID 

Acceptance criteria

- [ ] research some other SSO home page
- [ ] come up with a list of potential user stories for the page

**Comment by MilicaSequeira** [comment]
Researched SSO Home Pages:
https://auth0.com/single-sign-on
https://www.onelogin.com/product/sso
https://azure.microsoft.com/en-us/products/active-directory/
https://www.pingidentity.com/en/platform/capabilities/single-sign-on.html

Solution:
As a User I want to be greeted by an eye catching web page so that I remember being on the website and want to come back to it.
As a User I want to know what makes the product Im looking at useful for me.
As a User I want to have easy to understand explanation about the technology used so that I don’t feel lost or inferior or need to leave the website to search for explanations of special lingo.
As a user I want to know what is about the product that makes it standout so I can make an inform decision when choosing between options
As a User I want to know that it the product has been trusted my others (social proof) so I don’t get scammed.
As a user I want to know the price of the product to see if I can afford it or not.
As a user I want to know is it easy or difficult to use a product because new technology is scary.
As a user I want to be able to contact the company so that I can have my questions answered and feel valued.
As a user I want to know is the app secure against hacking so that I don’t have my data stollen.

**Comment by theblockstalk** [comment]
great research above! I think some of it can and should be used by the BD team - because those websites are the sales site for the clients that integrate SSO. however I have another perspective one what we want here
https://www.loom.com/share/fcf81879e5244a1d8c404a3ff30e9936

**Comment by theblockstalk** [comment]
perhaps this is an acceptable home page (not logged in)
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5492-26933&t=3i7ISwSGV7UulzX3-4

**Comment by theblockstalk** [comment]
ok, so if I go to account.google.com in a fresh browser I am redirected here (not logged in)
https://www.google.com/account/about
You saw what it looked like if I was Logged in

**Comment by MilicaSequeira** [comment]
other example
https://appleid.apple.com/

**Comment by MilicaSequeira** [comment]
As a User, I want to be greeted by an eye-catching web page so that I remember being on the website and want to return to it.
As a User I want to know how this product/service serves me so I can see is it a fit for me or not.
As a User, I want to learn about the Tonomy Account in laymen's terms so I understand it.
As a User, I want to learn about the Tonomy ID so I can see if can it help me in ways I didn't think of so it pays off getting it.
As a User I want to have multiple accesses to the login/sign up/get started buttons so I don't have to scroll to the other side of the page and get it, if I deem it suitable for me.
As a user, I would like to know the experiences of previous users.

**Comment by theblockstalk** [comment]
other ideas:
- As a prospective user, I want to be able to download tonomy ID, so I can start using Tonomy ID
- as a prospective user,  i want to know what apps I can use with Tonomy ID, so I can make a decision of whether it is useful for me
