### ISSUE TITLE
Research and design where to add a Captcha challenge

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#313]
Acceptance criteria

- [ ] Research where the best place to add a captcha challenge should be during create account flow
- [ ] update Tonomy ID design with captcha flow

Notes:
- assume we use https://www.hcaptcha.com/

**Comment by MilicaSequeira** [comment]
- It seems that using captcha isnt a very recommended rather than outdated method of human verification. Additionally  UX community  isnt supporting it either.

- Research results: 

Where to place them:
https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge-best-practices.html

Advantages and disadvanatges :
https://blog.cardinity.com/payment-security/why-should-you-use-captcha-on-a-website/#:~:text=Including%20a%20CAPTCHA%20form%2C%20can,it%20further%20into%20your%20website.

- Alternatives: 

https://datadome.co/bot-management-protection/captcha-recaptcha-alternatives/#:~:text=Blocking%20Simple%20Bots%20With%20a,won't%20be%20let%20through.
https://www.experienceux.co.uk/ux-blog/5-alternatives-to-captcha-that-wont-baffle-or-frustrate-users/

- Chat GPT summary:

 However, it is generally recommended to include the CAPTCHA challenge towards the end of the account creation process, just before the user submits their information.
By placing the CAPTCHA challenge at the end, you allow users to complete the rest of the form or registration process without interruption. This helps create a smoother user experience and reduces the frustration of encountering a CAPTCHA challenge too early in the process. Additionally, by placing it near the end, you can ensure that users are genuinely interested in completing the registration rather than being deterred by the CAPTCHA challenge at the very beginning.

Account Creation Flow:
CAPTCHA during the account creation flow helps ensure that the user registering for an account is a human and not an automated script or bot. By presenting a CAPTCHA challenge at this stage, you can prevent the creation of spam accounts, protect against fraudulent activities, and maintain the overall security and integrity of your user database.

Login Process:
CAPTCHA during the login process provides an additional layer of security against unauthorized access. It helps to verify that the login attempt is being made by a human and not by an automated program attempting to gain unauthorized access to user accounts. This can help protect user data, prevent brute force attacks, and enhance the overall security of your system.

**Comment by MilicaSequeira** [comment]
Because Tonomy account is created after the 2 steps ( Create username+ password) I would put captcha at the end of the create password page and made the create account button dissabled before the captcha is confirmed. After it is confirmed I would enable the create account button.

I would prefer to use I am human to choosing images because of the research done above.

**Comment by MilicaSequeira** [comment]
Take a look at the more fun options shown at the bottom row (document not owned by me but I can use it for internal prototype needs):
https://www.figma.com/file/w7foYcEHMeDufN78zJ7c2f/CAPTCHA-UI-Kit-(Community)?type=design&node-id=41%3A1&mode=design&t=D5NfLG7RsypqoScp-1

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5843-26443&mode=design&t=LvsKbdX8Lsd3TchQ-4
