### ISSUE TITLE
UI/UX review of the demo website

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#347]
Acceptance criteria

- [ ] UI/UX review of the demo website
- [ ] document any fixes or suggestions where the implementation does not match the design expectations

**Comment by theblockstalk** [comment]
1. VC sign button I need to press 2ce (done)
2. "Send payment" button should be disabled while waiting for transaction sign 100% (done)
3. We could split "Broadcasting" and "Confirmed by receiving node"(didn't understand)
4. Congratulations screen is very immediate and big. Maybe fade in would be good (done)
5. "Try signing document again" does not change mouse when mousover. Maybe its not a button?(done)
6. "How to use: Tonomy ID" is overlapped (done)
7. learn about the Antelope blockchain + learn about the W3C  Verifible Credentia-> link does not work (done)
8. learn about the Antelope blockchain --> Learn about the Antelope blockchain (capital L) (done)
9. Enter Demo should scroll user down to the demo (done)
10. sign using your Tonomy ID has a delay before it finishes(done)
11. when I click on a form field "Medication" the outline of the form is blue and then the changes to black (done)

**Comment by theblockstalk** [comment]
also feedback here:
https://docs.google.com/presentation/d/1OUPIfQxl16XGLTYeXmc20PZ7wglpYQh4f6aLROEl1zI/edit#slide=id.g1e4ec858772_0_13

**Comment by MilicaSequeira** [comment]
Chevron on code snippet is a v, not a chevron. (done)
Documentation is underlined and shouldn't be, also should be lifted higher so there is more space between it and the code snippet. (done)
Code snippet is lookign awesome!

HOME SCREEN
The image on the right is in 2 instances out of 3 too small. (done)
On the carousel screen, the image of use case of signing a document is bigger than the label that says its name, and the same for messaging peers (done)
The 3 dots on the carousel are missing
When the screen is on the use case of signing transaction it is higher than the other 2. You can see the pictures and icons jump up.  (done)
User name should be medium (Done)

SIGN TRANSACTION
Feature Name: Sign Transaction- make the font size smaller (done)
The actual amount, name of sender and recipient plus description should be medium thickness unlike, the labels. The labels should be like they already are in thickness but are missing the : . (done)
If Im on the bottom of the page and click to visit another page on the website I'll land on the bottom of the page instead of the top. (done)
Theres an error when i click send payment
The loading of the steps frame has a turquoise shadow but it shouldn't. The shadow should be just on the loading bar. (done)
The inner circle isnt centered with the outter circle in the loading steps ( if you cannor center it, make it smaller so so theres an even number of pixels of both circles) (done)
The button doesnt work, I keep getting errors even when i just load the page.

SIGN DOCUMENT
Everything mentioned in Sign Transaction applies here, too, except that the signing button works. (done)

CONGRATULATIONS:
TRY SIGNING THE DOCUMENT AGAIN is too big, make it a lot smaller (done)

NAVIGATION MENU: Doesnt indicate on which page are you on ( the icon and letters should be turqoise)
Tonomy ID and the icon shouldnt be able to be able to be hovered over. There should be a break so you cannot take your mouse all the way there.(done)
