### ISSUE TITLE
Research how to show data collection purpose

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#397]
Look into the following additional related questions and topics

- Consent screen to show purpose of data collection

https://gdpr.eu/data-privacy
https://cloudian.com/guides/data-protection/data-protection-principles-7-core-principles-of-the-gdpr
https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/a-guide-to-lawful-basis/

https://play.google.com/store/apps/datasafety?id=com.facebook.katana
https://play.google.com/store/apps/datasafety?id=foundation.tonomy.projects.tonomyiddemo
https://play.google.com/console/u/0/developers/9072114256093212658/app/4976366596665305716/app-content/data-privacy-security

Acceptance criteria

- [ ] document findings and suggestions from any additional research

**Comment by theblockstalk** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcitNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12fb4ece7b35f93e3e1ea8983ccb4cee9f1a6688/image.png)

**Comment by MilicaSequeira** [comment]
Most important stuff:
Purpose limitation
Fairness, lawfulness, and transparency
Data minimization
Storage limitation
Accuracy
Confidentiality and integrity
Accountability

GDPR Article 5(1)(b) states that: “Personal data shall be collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall not be considered to be incompatible with the initial purposes”


The lawful bases for processing are set out in Article 6 of the UK GDPR. At least one of these must apply whenever you process personal data:

(a) Consent: the individual has given clear consent for you to process their personal data for a specific purpose.

(b) Contract: the processing is necessary for a contract you have with the individual, or because they have asked you to take specific steps before entering into a contract.

(c) Legal obligation: the processing is necessary for you to comply with the law (not including contractual obligations).

(d) Vital interests: the processing is necessary to protect someone’s life.

(e) Public task: the processing is necessary for you to perform a task in the public interest or for your official functions, and the task or function has a clear basis in law.

(f) Legitimate interests: the processing is necessary for your legitimate interests or the legitimate interests of a third party, unless there is a good reason to protect the individual’s personal data which overrides those legitimate interests. (This cannot apply if you are a public authority processing data to perform your official tasks.)

**Comment by MilicaSequeira** [comment]
https://designmodo.com/ux-gdpr/
